package no.nav.familie.ef.søknad.mapper.kontrakt

const val TERMINBEKREFTELSE = "TERMINBEKREFTELSE";
const val DELT_BOSTED = "DELT_BOSTED";
const val SAMVÆRSAVTALE = "SAMVÆRSAVTALE";
const val SAMLIVSBRUDD = "SAMLIVSBRUDD";
const val BARN_BOR_HOS_SØKER = "BARN_BOR_HOS_SØKER";
const val BOR_PÅ_ULIKE_ADRESSER = "BOR_PÅ_ULIKE_ADRESSER";
const val SYKDOM = "SYKDOM";
const val SYKT_BARN = "SYKT_BARN";
const val BARNEPASS = "BARNEPASS";
const val BARNETILSYN_BEHOV = "BARNETILSYN_BEHOV";
const val UTDANNING = "UTDANNING";
const val ARBEIDSKONTRAKT = "ARBEIDSKONTRAKT";
const val ARBEIDSFORHOLD_REDUSERT_ARBEIDSTID = "ARBEIDSFORHOLD_REDUSERT_ARBEIDSTID";
const val ARBEIDSFORHOLD_OPPSIGELSE = "ARBEIDSFORHOLD_OPPSIGELSE";
const val LÆRLING = "LÆRLING";
const val INNGÅTT_EKTESKAP = "INNGÅTT_EKTESKAP";
const val SEPARASJON_ELLER_SKILSMISSE = "SEPARASJON_ELLER_SKILSMISSE";
const val UFORMELL_SEPARASJON_ELLER_SKILSMISSE = "UFORMELL_SEPARASJON_ELLER_SKILSMISSE";
const val IKKE_VILLIG_TIL_ARBEID = "IKKE_VILLIG_TIL_ARBEID";