package no.nav.familie.ef.søknad.mapper.kontrakt

enum class DokumentIdentifikator {
    TERMINBEKREFTELSE,
    DELT_BOSTED,
    SAMVÆRSAVTALE,
    SAMLIVSBRUDD,
    BARN_BOR_HOS_SØKER,
    BOR_PÅ_ULIKE_ADRESSER,
    SYKDOM,
    SYKT_BARN,
    BARNEPASS,
    BARNETILSYN_BEHOV,
    UTDANNING,
    ARBEIDSKONTRAKT,
    ARBEIDSFORHOLD_REDUSERT_ARBEIDSTID,
    ARBEIDSFORHOLD_OPPSIGELSE,
    LÆRLING,
    INNGÅTT_EKTESKAP,
    SEPARASJON_ELLER_SKILSMISSE,
    UFORMELL_SEPARASJON_ELLER_SKILSMISSE,
    IKKE_VILLIG_TIL_ARBEID,
    ETABLERER_VIRKSOMHET,

    TIDLIGERE_FAKTURAER,
    FAKTURA_BARNEPASSORDNING,
    AVTALE_BARNEPASSER,
    ARBEIDSTID,
    TRENGER_MER_PASS_ENN_JEVNALDREDE,
    FOR_SYK_TIL_Å_JOBBE
}