version: 2
registries:
  maven-repository-maven-pkg-github-com-navikt-fp-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles/
    username: x-access-token
    password: "${{secrets.MAVEN_REPOSITORY_MAVEN_PKG_GITHUB_COM_NAVIKT_FP_FELLES_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: no.nav.familie.felles:http-client
    versions:
    - 1.20210301162616_e3d53b9
    - 1.20210305114436_82a4a5e
    - 1.20210324134317_a391a3a
    - 1.20210329154135_57b92f0
    - 1.20210416135502_5bf9eff
  - dependency-name: no.nav.familie.felles:log
    versions:
    - 1.20210301162616_e3d53b9
    - 1.20210305114436_82a4a5e
    - 1.20210324134317_a391a3a
    - 1.20210329154135_57b92f0
    - 1.20210416135502_5bf9eff
  - dependency-name: no.nav.familie.kontrakter:enslig-forsorger
    versions:
    - 2.0_20210305131536_dd4cd5d
    - 2.0_20210308102146_90cb778
    - 2.0_20210416141710_97efcc5
  - dependency-name: no.nav.familie.kontrakter:felles
    versions:
    - 2.0_20210305131536_dd4cd5d
    - 2.0_20210308102146_90cb778
    - 2.0_20210416141710_97efcc5
  - dependency-name: no.finn.unleash:unleash-client-java
    versions:
    - 4.1.0
    - 4.2.1
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-allopen
    versions:
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-test-junit5
    versions:
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.31
    - 1.4.32
  - dependency-name: no.nav.security:token-validation-test-support
    versions:
    - 1.3.4
  - dependency-name: no.nav.security:token-validation-spring
    versions:
    - 1.3.4
  - dependency-name: io.mockk:mockk
    versions:
    - 1.10.6
    - 1.11.0
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.4
  - dependency-name: com.fasterxml.jackson.module:jackson-module-kotlin
    versions:
    - 2.12.2
  registries:
  - maven-repository-maven-pkg-github-com-navikt-fp-felles
