apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-soknad-api
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: navikt/familie-ef-soknad-api:{{version}}
  port: 8000
  liveness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /familie/alene-med-barn/soknad-api/internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/apigw/prod/familie-integrasjoner/familie-ef-soknad-api
        mountPath: /secrets/apikey/familie-integrasjoner
      - kvPath: /apikey/apigw/prod/familie-ef-mottak/familie-ef-soknad-api
        mountPath: /secrets/apikey/familie-ef-mottak
      - kvPath: /apikey/apigw/prod/tps-proxy.api.v1.innsyn/familie-ef-soknad-api
        mountPath: /secrets/apikey/tps-innsyn
      - kvPath: /kv/preprod/sbs/familie-ef-soknad-api/default
        mountPath: /var/run/secrets/nais.io/vault
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://familie-gcp.nav.no/familie/alene-med-barn/soknad-api
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-soknad
    outbound:
      rules:
        - application: familie-ef-mottak
      external:
        - host: login.microsoftonline.com
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
