apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-soknad-api
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8000
  liveness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /familie/alene-med-barn/soknad-api/internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/apigw/prod/familie-integrasjoner/familie-ef-soknad-api
        mountPath: /secrets/apikey/familie-integrasjoner
      - kvPath: /apikey/apigw/prod/familie-ef-mottak/familie-ef-soknad-api
        mountPath: /secrets/apikey/familie-ef-mottak
      - kvPath: /apikey/apigw/prod/tps-proxy.api.v1.innsyn/familie-ef-soknad-api
        mountPath: /secrets/apikey/tps-innsyn
      - kvPath: /apikey/apigw/prod/pdl-api/familie-ef-soknad-api
        mountPath: /secrets/apikey/pdl-api
      - kvPath: /apikey/apigw/prod/security-token-service-token/familie-ef-soknad-api
        mountPath: /secrets/apikey/security-token-service-token
      - kvPath: /kv/prod/sbs/familie-ef-soknad-api/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /serviceuser/data/prod/srvfam-ef-soknad-api
        mountPath: /var/run/secrets/srvfam-ef-soknad-api
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2Gi
      cpu: "1"
    requests:
      memory: 1Gi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://www.nav.no/familie/alene-med-barn/soknad-api
    - https://familie-ef-soknad-api.prod-sbs.nais.io
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
