apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-soknad-api
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: navikt/familie-ef-soknad-api:{{version}}
  port: 8000
  liveness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: /familie/alene-med-barn/soknad-api/internal/prometheus
  ingresses:
      - https://familie-ef-soknad-api.dev-adeo.no/
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-soknad
    outbound:
      external:
        - host: login.microsoftonline.com
        - host: unleashproxy.nais.oera.no
        - host: api-gw-q2.oera.no
        - host: familie-intregrasjoner.dev-fss-pub.nais.io
  gcp:
    buckets:
      - name: nav-familie-ef-s3
  webproxy: false
  vault:
    enabled: false
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie
    - secret: ef-soknad-api
