apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-soknad-api
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: navikt/familie-ef-soknad-api:{{version}}
  port: 8000
  liveness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /familie/alene-med-barn/soknad-api/internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/apigw/dev/familie-integrasjoner/familie-ef-soknad-api_q2/x-nav-apiKey
        mountPath: /secrets/apikey/familie-integrasjoner
      - kvPath: /apikey/apigw/dev/familie-ef-mottak/familie-ef-soknad-api_q2/x-nav-apiKey
        mountPath: /secrets/apikey/familie-ef-mottak
      - kvPath: /apikey/apigw/dev/tps-proxy.api.v1.innsyn/familie-ef-soknad-api_q2/x-nav-apiKey
        mountPath: /secrets/apikey/tps-innsyn
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://www-q0.nav.no/familie/alene-med-barn/soknad-api
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
