server:
  port: 8091
  servlet:
    context-path: /

familie:
  ef:
    mottak:
      url: http://localhost:8092/api/
      username: ${FAMILIE_EF_MOTTAK_USERNAME:}
      password: ${FAMILIE_EF_MOTTAK_PASSWORD:}
s3:
  endpoint: http://s3.nais-rook.svc.nais.local/
  region: us-east-1
  username: user
  password: pwd
  passphrase: pass
  attachmentMazSize: 20
funksjonsbrytere:
  enabled: false
  unleashApiUrl: http://localhost:4242/api
  unleashEnv: local
  unleashAppName: familie-ef-soknad-api

cors:
  allowed_origins:
    - "http://localhost:3000"

#logging:
#  config: classpath:logback-spring-test.xml
