application:
  name: familie-ef-soknad-api
server:
  port: 8000
  servlet:
    context-path: /

familie:
  ef:
    mottak:
      url: https://api-gw.oera.no/familie-ef-mottak/api/
      username: ${FAMILIE_EF_MOTTAK_USERNAME}
      password: ${FAMILIE_EF_MOTTAK_PASSWORD}
    oppslag:
      url: url
      key: key
    soknad:
      regelverk:
        maks:
          alder:
            barn: 18
      health:
        indicator:
          detailed: true
      tps:
        innsyn:
          url: https://api-gw.oera.no/tps-proxy/api/v1/innsyn/
          bruker: ${FAMILIE_EF_SOKNAD_TPS_INNSYN_PROXY_USER} #<Ligger i vault>
          passord: ${FAMILIE_EF_SOKNAD_TPS_INNSYN_PROXY_PASSWORD} #<Ligger i vault>
      s3:
        endpoint: http://s3.nais-rook
        region: us-east-1
        username: nousername #${FAMILIE_EF_SOKNAD_S3_USERNAME}#<Ligger i vault>
        password: nopwd #${FAMILIE_EF_SOKNAD_S3_PASSWORD}#<Ligger i vault>
        passphrase: nopwd #${FAMILIE_EF_SOKNAD_S3_PASSPHRASE}#<Ligger i vault>
        attachmentMazSize: 20
    virus:
      enabled: true
      url: http://clamav.nais.svc.nais.local/scan
    funksjonsbrytere:
      enabled: true
      unleash:
        apiUrl: https://unleashproxy.nais.oera.no/api/ #NB prod
        environment: ${NAIS_CLUSTER_NAME:}
        applicationName: ${NAIS_APP_NAME:}

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics.export.prometheus.enabled: true
  metrics.web.server.auto-time-requests: true

cors:
  allowed_origins:

