server:
  port: 8091

familie:
  ef:
    mottak:
      uri: http://localhost:8092/
      brukernavn: none
      passord: none
tps:
  innsyn:
    uri: https://api-gw.oera.no/tps-proxy/api/v1/innsyn/
    brukernavn: user
    passord: pwd
s3:
  uri: http://s3.nais-rook.svc.nais.local/
  region: us-east-1
  brukernavn: user
  passord: pwd
  passordfrase: pass
  maxMbVedlegg: 20
funksjonsbrytere:
  enabled: false
  unleash:
    uri: http://localhost:4242/api
    environment: local
    applicationName: familie-ef-soknad-api

cors:
  allowed_origins:
    - "http://localhost:3000"

#logging:
#  config: classpath:logback-spring-test.xml
