familie:
  ef:
    mottak:
      uri: https://api-gw-q0.oera.no/familie-ef-mottak/api/
tps:
  innsyn:
    uri:  https://api-gw-q0.oera.no/tps-proxy/api/v1/innsyn/

cors:
  allowed_origins:
    - "https://familie-ef-soknad.nais.oera-q.local"
    - "https://familie-ef-soknad-api.nais.oera-q.local"
