server:
  port: 8000
  servlet:
    context-path: /

familie:
  ef:
    mottak:
      url: https://api-gw.oera.no/familie-ef-mottak/api/
      username: ${FAMILIE_EF_MOTTAK_USERNAME}
      password: ${FAMILIE_EF_MOTTAK_PASSWORD}
    oppslag:
      url: url
      key: key

health:
  indicator:
    detailed: true
s3:
  endpoint: http://s3.nais-rook
  region: us-east-1
  username: nousername #${FAMILIE_EF_SOKNAD_S3_USERNAME}#<Ligger i vault>
  password: nopwd #${FAMILIE_EF_SOKNAD_S3_PASSWORD}#<Ligger i vault>
  passphrase: nopwd #${FAMILIE_EF_SOKNAD_S3_PASSPHRASE}#<Ligger i vault>
  attachmentMazSize: 20
virus:
  enabled: true
  uri: http://clamav.nais.svc.nais.local/scan
funksjonsbrytere:
  enabled: true
  unleash:
    apiUrl: https://unleashproxy.nais.oera.no/api/
    env: ${NAIS_CLUSTER_NAME:}
    appName: ${NAIS_APP_NAME:}

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics.export.prometheus.enabled: true
  metrics.web.server.auto-time-requests: true

cors:
  allowed_origins:
    - "https://familie-ef-soknad.nais.oera.no"
    - "https://familie-ef-soknad-api.nais.oera.no"
