server:
  port:
  servlet:
    context-path: /


familie:
  ef:
    mottak:
      url: https://api-gw.oera.no/familie-ef-mottak/api/
      key: key
    oppslag:
      url: https://api-gw.oera.no/familie-ef-oppslag/api/
      key: key
    soknad:
      s3:
        endpoint: http://s3.nais-rook
        region: us-east-1
        username: ${FAMILIE_EF_SOKNAD_S3_USERNAME}#<Ligger i vault>
        password: ${FAMILIE_EF_SOKNAD_S3_PASSWORD}#<Ligger i vault>
        passphrase: ${FAMILIE_EF_SOKNAD_S3_PASSPHRASE}#<Ligger i vault>
        attachmentMazSize: 20
    virus:
      enabled: true
      url: http://clamav.nais.svc.nais.local/scan
