application:
  name: familie-ef-soknad-api
server:
  port: 8000
  servlet:
    context-path: /

familie:
  ef:
    mottak:
      uri: https://api-gw.oera.no/familie-ef-mottak/api/
      brukernavn: ${FAMILIE_EF_MOTTAK_BRUKERNAVN}
      passord: ${FAMILIE_EF_MOTTAK_PASSORD}
regelverk:
  alder:
    maks: 18
health:
  indicator:
    detailed: true
tps:
  innsyn:
    uri: https://api-gw.oera.no/tps-proxy/api/v1/innsyn/
    brukernavn: ${TPS_INNSYN_PROXY_BRUKERNAVN} #<Ligger i vault>
    passord: ${TPS_INNSYN_PROXY_PASSORD} #<Ligger i vault>
s3:
  uri: http://s3.nais-rook
  region: us-east-1
  brukernavn: ${S3_BRUKERNAVN} #<Ligger i vault>
  passord: ${S3_PASSORD} #<Ligger i vault>
  passordfrase: ${S3_PASSORDFRASE} #<Ligger i vault>
  maxMbVedlegg: 20
virus:
  enabled: true
  uri: http://clamav.nais.svc.nais.local/scan
funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleashproxy.nais.oera.no/api/
    environment: ${NAIS_CLUSTER_NAME:}
    applicationName: ${NAIS_APP_NAME:}

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        auto-time-requests: true

cors:
  allowed_origins:
