application:
  name: familie-ef-soknad-api
server:
  port: 8000
  servlet:
    context-path: /familie/alene-med-barn/soknad-api

familie:
  ef:
    mottak:
      uri: https://api-gw.oera.no/familie-ef-mottak/api
  dokument:
    uri: https://www.nav.no/familie/alene-med-barn/mellomlagring/api
  integrasjoner:
    uri:  https://api-gw.oera.no/familie-integrasjoner/api

regelverk:
  alder:
    maks: 18
health:
  indicator:
    detailed: true
tps:
  innsyn:
    uri: https://api-gw.oera.no/tps-proxy/api/v1/innsyn/

funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleashproxy.nais.oera.no/api/
    environment: ${NAIS_CLUSTER_NAME:}
    applicationName: ${NAIS_APP_NAME:}

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        auto-time-requests: true

cors:
  allowed_origins:
    - "https://familie-ef-soknad.nais.oera.no"
    - "https://familie-ef-soknad-api.nais.oera.no"
    - "https://www.nav.no/familie/alene-med-barn/soknad"
    - "https://www.nav.no/familie/alene-med-barn/soknad-api"

no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
    accepted_audience: ${ACCEPTEDAUDIENCE}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: selvbetjening-idtoken
