server:
  port: 8091
  servlet:
    context-path: 

familie:
  integrasjoner:
    uri: http://localhost:8085/api
    passord: pwdIntegrasjoner
  ef:
    mottak:
      uri: http://localhost:8092/api
      passord: pwdMottak
tps:
  innsyn:
    uri: http://localhost:8091/mockapi/
    passord: pwdInnsyn

funksjonsbrytere:
  enabled: false
  unleash:
    uri: http://localhost:4242/api
    environment: local
    applicationName: familie-ef-soknad-api

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

logging:
  config: classpath:logback-spring-test.xml

no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
    proxyurl:
