cors:
  allowed_origins:
    - "https://www-q0.nav.no/familie/alene-med-barn/soknad"
    - "https://familie.dev.nav.no/familie/alene-med-barn/soknad"

familie:
  dokument.uri: http://familie-dokument/api
  ef.mottak.uri: https://familie-ef-mottak.dev-fss-pub.nais.io/api
  integrasjoner.uri: https://familie-integrasjoner.dev-fss-pub.nais.io/api

PDL_URL: https://pdl-api.dev-fss-pub.nais.io
PDL_SCOPE: api://dev-fss.pdl.pdl-api/.default

MOTTAK_SCOPE: dev-fss:teamfamilie:familie-ef-mottak