server:
  port: 8000
  servlet:
    context-path: /

familie:
  ef:
    heath:
      indicator:
        detailed: true
    mottak:
      url: https://api-gw-q0.oera.no/familie-ef-mottak/api/
      key: key

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics.export.prometheus.enabled: true
  metrics.web.server.auto-time-requests: true
