familie:
  dokument:
    uri: https://www-q0.nav.no/familie/alene-med-barn/mellomlagring/api
  ef:
    mottak:
      uri: https://api-gw-q0.oera.no/familie-ef-mottak/api
      passord: ${FAMILIE_EF_MOTTAK_PASSORD}
  integrasjoner:
    uri:  https://api-gw-q2.oera.no/familie-integrasjoner/api
    passord: ${FAMILIE_INTEGRASJONER_PASSORD}

tps:
  innsyn:
    uri:  https://api-gw-q2.oera.no/tps-proxy/api/v1/innsyn/
    passord: ${TPS_INNSYN_PROXY_PASSORD}

funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleash.dev-adeo.no/api/
    environment: ${NAIS_CLUSTER_NAME:}
    applicationName: ${NAIS_APP_NAME:}

cors:
  allowed_origins:
    - "https://www.dev.nav.no/familie/alene-med-barn/soknad"
    - "https://www.dev.nav.no/familie/alene-med-barn/soknad-api"


no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    accepted_audience: ${ACCEPTEDAUDIENCE}
    cookie_name: selvbetjening-idtoken
