familie:
  ef:
    mottak:
      uri: https://familie-ef-mottak.dev-fss-pub.nais.io/api
      audience: dev-fss:teamfamilie:familie-ef-mottak
  integrasjoner:
    uri:  https://familie-integrasjoner.dev-fss-pub.nais.io/api

cors:
  allowed_origins:
    - "https://www-q0.nav.no/familie/alene-med-barn/soknad"
    - "https://www-q0.nav.no"
    - "https://familie.dev.nav.no/familie/alene-med-barn/soknad"
    - "https://ensligmorellerfar.dev.nav.no"s

PDL_URL: https://pdl-api.dev-fss-pub.nais.io
PDL_AUDIENCE: dev-fss:pdl:pdl-api
PDL_SCOPE: api://dev-fss.pdl.pdl-api/.default
