server:
  port: 8000
  servlet:
    context-path: /

familie:
  ef:
    heath:
      indicator:
        detailed: true
    mottak:
      url: https://api-gw.oera.no/familie-ef-mottak/api/
      key: key
    oppslag:
      url: https://api-gw.oera.no/familie-ef-oppslag/api/
      key: key
    soknad:
      s3:
        endpoint: http://s3.nais-rook
        region: us-east-1
        username: nousername #${FAMILIE_EF_SOKNAD_S3_USERNAME}#<Ligger i vault>
        password: nopwd #${FAMILIE_EF_SOKNAD_S3_PASSWORD}#<Ligger i vault>
        passphrase: nopwd #${FAMILIE_EF_SOKNAD_S3_PASSPHRASE}#<Ligger i vault>
        attachmentMazSize: 20
    virus:
      enabled: true
      url: http://clamav.nais.svc.nais.local/scan
    funksjonsbrytere:
      enabled: false

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics.export.prometheus.enabled: true
  metrics.web.server.auto-time-requests: true