familie:
  ef:
    mottak:
      uri: http://familie-ef-mottak/api
      audience: dev-gcp:teamfamilie:familie-ef-mottak
  integrasjoner:
    uri:  https://familie-integrasjoner-q1.dev-fss-pub.nais.io/api
    scope: api://dev-fss.teamfamilie.familie-integrasjoner-q1/.default

cors:
  allowed_origins:
    - "https://www-q0.nav.no/familie/alene-med-barn/soknad"
    - "https://www-q0.nav.no"
    - "https://familie.dev.nav.no/familie/alene-med-barn/soknad"
    - "https://ensligmorellerfar.dev.nav.no"

PDL_URL: https://pdl-api-q1.dev-fss-pub.nais.io
PDL_AUDIENCE: dev-fss:pdl:pdl-api-q1
PDL_SCOPE: api://dev-fss.pdl.pdl-api-q1/.default
