familie:
  ef:
    mottak:
      url: https://api-gw-q0.oera.no/familie-ef-mottak/api/

cors:
  allowed_origins:
    - "https://familie-ef-soknad.nais.oera-q.local"
    - "https://familie-ef-soknad-api.nais.oera-q.local"
