server:
  port: 8091
  servlet:
    context-path:

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB
familie:
  integrasjoner:
    uri: http://localhost:8085/api
    passord: pwdIntegrasjoner
  ef:
    mottak:
      uri: http://localhost:8092/api
      passord: pwdMottak
  dokument:
    uri: http://localhost:8082/api

tps:
  innsyn:
    uri: http://localhost:8091/mockapi/
    passord: pwdInnsyn

pdl:
  passord: pdlPassord

sts:
  passord: stsPassord

funksjonsbrytere:
  enabled: false
  unleash:
    uri: http://localhost:4242/api
    environment: local
    applicationName: familie-ef-soknad-api

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

logging:
  config: classpath:logback-spring-test.xml

no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
    proxyurl:
