application:
  name: familie-ef-soknad-api
server:
  port: 8000
  servlet:
    context-path: /familie/alene-med-barn/soknad-api

familie:
  ef:
    mottak:
      uri: https://api-gw.oera.no/familie-ef-mottak/api
  dokument:
    uri: https://www.nav.no/familie/dokument/api
  integrasjoner:
    uri:  https://api-gw.oera.no/familie-integrasjoner/api

regelverk:
  alder:
    maks: 18
health:
  indicator:
    detailed: true
tps:
  innsyn:
    uri: https://api-gw.oera.no/tps-proxy/api/v1/innsyn/

funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleash.nais.io/api/
    environment: ${NAIS_CLUSTER_NAME:}
    applicationName: ${NAIS_APP_NAME:}

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true

cors:
  allowed_origins:
    - "https://familie-ef-soknad.nais.oera.no"
    - "https://familie-ef-soknad-api.nais.oera.no"
    - "https://www.nav.no/familie/alene-med-barn/soknad"
    - "https://www.nav.no/familie/alene-med-barn/soknad-api"

no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: selvbetjening-idtoken
  client.registration:
    mottak:
      resource-url: ${familie.ef.mottak.uri}
      well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
      grant-type: urn:ietf:params:oauth:grant-type:token-exchange
      token-exchange:
        audience: ${MOTTAK_AUDIENCE}
      authentication:
        client-id: ${TOKEN_X_CLIENT_ID}
        client-auth-method: private_key_jwt
        client-jwk: ${TOKEN_X_PRIVATE_JWK}

PDL_URL: https://api-gw.oera.no/pdl-api
STS_URL: https://api-gw.oera.no/security-token-service/rest/v1/sts/token?grant_type=client_credentials&scope=openid

MOTTAK_AUDIENCE: prod-fss:teamfamilie:familie-ef-mottak