familie:
  dokument:
    uri: https://www-q0.nav.no/familie/alene-med-barn/mellomlagring/api
  ef:
    mottak:
      uri: https://api-gw-q0.oera.no/familie-ef-mottak/api
  integrasjoner:
    uri:  https://api-gw-q2.oera.no/familie-integrasjoner/api

tps:
  innsyn:
    uri:  https://api-gw-q2.oera.no/tps-proxy/api/v1/innsyn/

cors:
  allowed_origins:
    - "https://familie-ef-soknad.nais.oera-q.local"
    - "https://familie-ef-soknad-api.nais.oera-q.local"
    - "https://www-q0.nav.no/familie/alene-med-barn/soknad"
    - "https://www-q0.nav.no/familie/alene-med-barn/soknad-api"


no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: selvbetjening-idtoken
