application:
  name: familie-ef-soknad-api
server:
  port: 8000
  servlet:
    context-path: /familie/alene-med-barn/soknad-api

spring:
  main:
    allow-bean-definition-overriding: true

springdoc:
  packagesToScan: no.nav.familie.ef.søknad
  pathsToMatch: /v3/api-docs,/api/**
  swagger-ui:
    disable-swagger-default-url: true

familie:
  ef:
    mottak:
      uri: http://familie-ef-mottak/api
      audience: prod-gcp:teamfamilie:familie-ef-mottak
  integrasjoner:
    uri:  https://familie-integrasjoner.prod-fss-pub.nais.io/api
    scope: ${FAMILIE_INTEGRASJONER_SCOPE}

regelverk:
  alder:
    maks: 18
health:
  indicator:
    detailed: true

funksjonsbrytere:
  enabled: true
  unleash:
    uri: https://unleash.nais.io/api/
    environment: ${NAIS_CLUSTER_NAME:}
    applicationName: ${NAIS_APP_NAME:}

management:
  endpoint:
    health:
      show-details: always
      enabled: true
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true

cors:
  allowed_origins:
    - "https://www.nav.no/familie/alene-med-barn/soknad"
    - "https://www.nav.no/familie/alene-med-barn/soknad-api"
    - "https://www.nav.no/familie/alene-med-barn/ettersending"

no.nav.security.jwt:
  issuer:
    selvbetjening:
      discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
      accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
      cookie_name: selvbetjening-idtoken
    tokenx:
      discovery-url: ${TOKEN_X_WELL_KNOWN_URL}
      accepted-audience: ${TOKEN_X_CLIENT_ID}
  client.registration:
    mottak:
      resource-url: ${familie.ef.mottak.uri}
      well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
      grant-type: urn:ietf:params:oauth:grant-type:token-exchange
      token-exchange:
        audience: ${familie.ef.mottak.audience}
      authentication:
        client-id: ${TOKEN_X_CLIENT_ID}
        client-auth-method: private_key_jwt
        client-jwk: ${TOKEN_X_PRIVATE_JWK}
    pdl:
      resource-url: ${PDL_URL}
      well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
      grant-type: urn:ietf:params:oauth:grant-type:token-exchange
      token-exchange:
        audience: ${PDL_AUDIENCE}
      authentication:
        client-id: ${TOKEN_X_CLIENT_ID}
        client-auth-method: private_key_jwt
        client-jwk: ${TOKEN_X_PRIVATE_JWK}
    pdl-clientcredentials:
      resource-url: ${PDL_URL}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${PDL_SCOPE}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

PDL_URL: https://pdl-api.prod-fss-pub.nais.io
PDL_AUDIENCE: prod-fss:pdl:pdl-api
PDL_SCOPE: api://prod-fss.pdl.pdl-api/.default