apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-soknad-api
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8000
  liveness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /familie/alene-med-barn/soknad-api/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /familie/alene-med-barn/soknad-api/internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses:
    - https://familie-ef-soknad-api.intern.dev.nav.no
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-soknad
        - application: familie-ef-ettersending
    outbound:
      rules:
        - application: familie-ef-mottak
      external:
        - host: unleash.nais.io
        - host: familie-integrasjoner.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: familie-ef-mottak.dev-fss-pub.nais.io
  envFrom:
    - secret: familie
    - secret: ef-soknad-api
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev